{{/*
Create the service account of alert manager to use
*/}}
{{- if .Values.monitors.alertManager.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: alertmanager-main
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- end -}}

