apiVersion: v1
kind: Service
metadata:
  labels:
    app: grafana
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  name: grafana
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: http
    port: {{ .Values.monitors.grafana.port }}
    targetPort: http
  selector:
    app: grafana
  type: {{ .Values.monitors.grafana.serviceType }}

