{{/*
Create the service account of alert manager to use
*/}}
{{- if .Values.monitors.grafana.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: grafana
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- end -}}