apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-ini
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
{{ (.Files.Glob "config/grafana.ini").AsConfig | indent 2 }}