{{/*
Create the service account of kubestatemetrics to use
*/}}
{{- if .Values.monitors.kubeStateMetrics.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: kube-state-metrics
    app.kubernetes.io/version: {{ .Values.monitors.kubeStateMetrics.version }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  name: kube-state-metrics
  namespace: {{ .Release.Namespace }}
{{- end -}}


