{{/*
Create the service account of node exporter to use
*/}}
{{- if .Values.monitors.nodeExporter.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: node-exporter
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- end -}}