apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app.kubernetes.io/name: node-exporter
    app.kubernetes.io/version: {{ .Values.monitors.nodeExporter.version}}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  name: node-exporter
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: node-exporter
  template:
    metadata:
      labels:
        app.kubernetes.io/name: node-exporter
        app.kubernetes.io/version: {{ .Values.monitors.nodeExporter.version}}
    spec:
      containers:
      - args:
        - {{"--web.listen-address=127.0.0.1:"}}{{ .Values.monitors.nodeExporter.port }}
        - --path.procfs=/host/proc
        - --path.sysfs=/host/sys
        - --path.rootfs=/host/root
        - --no-collector.wifi
        - --no-collector.hwmon
        - --collector.filesystem.ignored-mount-points=^/(dev|proc|sys|var/lib/docker/.+|var/lib/kubelet/pods/.+)($|/)
        image: {{ .Values.monitors.nodeExporter.repo }}{{"/"}}{{ .Values.monitors.nodeExporter.image }}:{{ .Values.monitors.nodeExporter.version}}
        name: node-exporter
        resources:
{{ toYaml .Values.monitors.nodeExporter.resources | indent 10 }}
        volumeMounts:
        - mountPath: /host/proc
          mountPropagation: HostToContainer
          name: proc
          readOnly: true
        - mountPath: /host/sys
          mountPropagation: HostToContainer
          name: sys
          readOnly: true
        - mountPath: /host/root
          mountPropagation: HostToContainer
          name: root
          readOnly: true
      - args:
        - --logtostderr
        - {{"--secure-listen-address=[$(IP)]:"}}{{ .Values.monitors.nodeExporter.port }}
        - --tls-cipher-suites=TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
        - {{"--upstream=http://127.0.0.1:"}}{{ .Values.monitors.nodeExporter.port }}{{"/"}}
        env:
        - name: IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        image: {{ .Values.monitors.kubeRBACProxy.repo }}{{"/"}}{{ .Values.monitors.kubeRBACProxy.image }}:{{ .Values.monitors.kubeRBACProxy.version }}
        name: kube-rbac-proxy
        ports:
        - containerPort: {{ .Values.monitors.nodeExporter.port }}
          hostPort: {{ .Values.monitors.nodeExporter.port }}
          name: https
        resources:
          limits:
            cpu: 20m
            memory: 40Mi
          requests:
            cpu: 10m
            memory: 20Mi
        securityContext:
          runAsGroup: 65532
          runAsNonRoot: true
          runAsUser: 65532
      hostNetwork: true
      hostPID: true
      nodeSelector:
        kubernetes.io/os: linux
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
      serviceAccountName: node-exporter
      tolerations:
      - operator: Exists
      volumes:
      - hostPath:
          path: /proc
        name: proc
      - hostPath:
          path: /sys
        name: sys
      - hostPath:
          path: /
        name: root
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 10%
    type: RollingUpdate

