{{/*
Create the cluster role of node exporter to use
*/}}
{{- if .Values.monitors.nodeExporter.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: polardbx-node-exporter
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: polardbx-node-exporter
subjects:
- kind: ServiceAccount
  name: node-exporter
  namespace: {{ .Release.Namespace }}
{{- end -}}