apiVersion: v1
kind: Service
metadata:
  labels:
    prometheus: k8s
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  name: prometheus-k8s
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: web
    port: 9090
    targetPort: web
  selector:
    app: prometheus
    prometheus: k8s
  sessionAffinity: ClientIP
  type: {{ .Values.monitors.prometheus.serviceType }}

