{{/*
Create the role of prometheus to use
*/}}
{{- if .Values.monitors.prometheus.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: polardbx-prometheus-k8s-config
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: polardbx-prometheus-k8s-config
subjects:
- kind: ServiceAccount
  name: prometheus-k8s
  namespace: {{ .Release.Namespace }}
{{- end -}}