{{/*
Create the cluster role of prometheus operator to use
*/}}
{{- if .Values.monitors.prometheusOperator.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/name: prometheus-operator
    app.kubernetes.io/version: v0.44.1
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  name: prometheus-operator
  namespace: {{ .Release.Namespace }}
{{- end -}}