{{/*
Create the cluster role of prometheus to use
*/}}
{{- if .Values.monitors.prometheus.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: polardbx-prometheus-k8s
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: polardbx-prometheus-k8s
subjects:
- kind: ServiceAccount
  name: prometheus-k8s
  namespace: {{ .Release.Namespace }}
{{- end -}}