{{/*
Create the role of prometheus to use
*/}}
{{- if .Values.monitors.prometheus.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus-k8s
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- end -}}