apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-adapter
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.monitors.prometheusAdapter.replicas }}
  selector:
    matchLabels:
      name: prometheus-adapter
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        name: prometheus-adapter
    spec:
      containers:
      - args:
        - --cert-dir=/var/run/serving-cert
        - --config=/etc/adapter/config.yaml
        - --logtostderr=true
        - --metrics-relist-interval=1m
        - --prometheus-url=http://prometheus-k8s.polardbx-monitor.svc.cluster.local:9090/
        - --secure-port=6443
        image: {{ .Values.monitors.prometheusAdapter.repo}}{{"/"}}{{ .Values.monitors.prometheusAdapter.image}}:{{ .Values.monitors.prometheusAdapter.version}}
        name: prometheus-adapter
        resources:
{{ toYaml .Values.monitors.prometheusAdapter.resources | indent 10 }}
        ports:
        - containerPort: 6443
        volumeMounts:
        - mountPath: /tmp
          name: tmpfs
          readOnly: false
        - mountPath: /var/run/serving-cert
          name: volume-serving-cert
          readOnly: false
        - mountPath: /etc/adapter
          name: config
          readOnly: false
      {{- with .Values.monitors.prometheusAdapter.nodeSelector }}
      nodeSelector:
      {{ toYaml . | indent 2 }}
      {{- end }}
      serviceAccountName: prometheus-adapter
      volumes:
      - emptyDir: {}
        name: tmpfs
      - emptyDir: {}
        name: volume-serving-cert
      - configMap:
          name: adapter-config
        name: config

