{{/*
Create the service account of prometheus adaptor to use
*/}}
{{- if .Values.monitors.prometheusAdapter.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus-adapter
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- end -}}