apiVersion: v1
kind: Service
metadata:
  labels:
    name: prometheus-adapter
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  name: prometheus-adapter
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: https
    port: 443
    targetPort: 6443
  selector:
    name: prometheus-adapter

