{{/*
Create the cluster role of prometheus adaptor to use
*/}}
{{- if .Values.monitors.prometheusAdapter.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: polardbx-resource-metrics-auth-reader
  namespace: kube-system
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: extension-apiserver-authentication-reader
subjects:
- kind: ServiceAccount
  name: prometheus-adapter
  namespace: {{ .Release.Namespace }}
{{- end -}}